name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  lint:
    name: Code Quality and Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
        
    - name: Make scripts executable
      run: |
        chmod +x ./tools/lint.sh
        chmod +x ./build.sh
        chmod +x ./test.sh
        
    - name: Run linting
      run: ./tools/lint.sh
      
    - name: Upload lint results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: lint-results
        path: |
          *.log
          lint-*.txt
        retention-days: 7
